version: "3.8"
services:
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    env_file:
      - ./config/production.env
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.production
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    env_file:
      - ./config/production.env

volumes:
  mongo-data: